#spring.application.name=rcspushapi
##kafka.bootstrap-servers=68.183.91.51:9092
#kafka.bootstrap-servers=91.99.191.216:9092
##spring.data.mongodb.uri=mongodb://68.183.91.51:28017/vts_genesis_rcs
##spring.data.mongodb.authentication-database=admin
##spring.data.mongodb.username=root
##spring.data.mongodb.password=Admin@123021
#
#spring.data.mongodb.uri=mongodb://admin:A&12345@91.99.191.216:28017/vts_genesis_rcs?authSource=admin
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=A&12345
#mongodb.database.name=vts_genesis_rcs
#
#server.port=8081
#push.api.instance.id= 9837
#push.api.kafka.topic=push.api.message.receiver
#push.api.kafka.topic.rich=push.api.message.receiver.rich
#spring.cache.type=redis
#spring.redis.host=13.232.84.138
#spring.redis.port=6379
#
#spring.redis.password=
#spring.redis.max.total.con=30
#spring.redis.min.idle.con=2
#spring.redis.max.idle.con=5
#dotgo.checkUrl=https://api.dotgo.com/rcs/bot/v1/%Bot_Id%/contactCapabilities?userContact=%Mobile%
#dotgo.bulkCapabilityUrl=https://api.dotgo.com/rcs/bot/v1/%Bot_Id%/rcsEnabledContacts
#jio.url.sent.message=https://stg-msg-businessmessaging.jio.com/v1/messaging/users/%Mobile%/assistantMessages/async
#jio.auth=https://stg-tgs-businessmessaging.jio.com/auth/oauth/token?grant_type=client_credentials
#jio.checkUrl=https://stg-msg-businessmessaging.jio.com/v1/messaging/users/%Mobile%/capabilities
#jio.bulkCapabilityUrl=https://stg-msg-businessmessaging.jio.com/v1/messaging/usersBatchGet
#vodafone.url.sent.message=https://api.virbm.com/rcs/v1/phones/%Mobile%/agentMessages/async?botId=%Bot_Id%&messageId=%MSG_Id%
#vodafone.auth=https://api.virbm.com/rcs/oauth/token?grant_type=client_credentials
#vodafone.checkUrl=https://api.virbm.com/rcs/v1/phones/%Mobile%/capabilities?botId=%Bot_Id%&requestId=%request_id%
#vodafone.bulkCapabilityUrl=https://api.virbm.com/rcs/v1/phones/capabilities/bulk?botId=%bot_id%&requestId=%request_id%
#
#dotgo.url.sent.message = https://api.dotgo.com/rcs/v1/phones/%Mobile%/agentMessages/async?botId=%Bot_Id%&messageId=%MSG_Id%
#dotgo.auth=https://auth.dotgo.com/auth/oauth/token?grant_type=client_credentials
##dotgo.clientId=29PiXKa2RX1r4r34
##dotgo.clientSecert=OulBD8naPMGAmZM0f3xJQk66l1MlVfVL
#dotgo.clientId=1x0kiKmR0Sd1WJuU
#dotgo.clientSecert=DMeId0u9PZpKiPVWXaZTwnq61dA9OZew
#jiocx.bulkCapabilityUrl=
#
#new.vodafone.auth=https://api.virbm.com/rcs/oauth/token
#new.vodafone.url.sent.message=https://api.virbm.com/rcs/v1/phones/%Mobile%/agentMessages?botId=%Bot_Id%&messageId=%MSG_Id%
#new.vodafone.checkUrl=https://api.virbm.com/rcs/v1/phones/%Mobile%/capabilities?botId=%Bot_Id%&requestId=%request_id%
#new.vodafone.bulkCapabilityUrl=https://api.virbm.com/rcs/v1/phones/capabilities/bulk?botId=%Bot_Id%&requestId=%request_id%
#new.vodafone.template=https://tmapi.virbm.com/templateapi/v1/bots/
#new.vodafone.template.auth=https://tmapi.virbm.com/templateapi/oauth/token/





spring.application.name=rcspushapi
kafka.bootstrap-servers=100.64.195.119:9092
spring.data.mongodb.uri=mongodb://100.64.195.111:27017/telspiel_genesis_rcs
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=appuser
spring.data.mongodb.password=P@mong12
server.port=7079

push.api.instance.id= 9837
push.api.kafka.topic=rcs.push.api.message.receiver
push.api.kafka.topic.rich=push.api.message.receiver.rich

spring.cache.type=redis

spring.redis.host=100.64.195.111
spring.redis.port=6379
spring.redis.password=p@ssY$Ay@h00
spring.redis.max.total.con=20
spring.redis.min.idle.con=2
spring.redis.max.idle.con=5




spring.redis2.max.total.con=30
spring.redis2.min.idle.con=2
spring.redis2.max.idle.con=5
dotgo.url.sent.message=https://api.dotgo.com/rcs/v1/phones/%Mobile%/agentMessages/async?botId=%Bot_Id%&messageId=%MSG_Id%
dotgo.auth=https://auth.dotgo.com/auth/oauth/token?grant_type=client_credentials
#dotgo.clientId=29PiXKa2RX1r4r34
#dotgo.clientSecert=OulBD8naPMGAmZM0f3xJQk66l1MlVfVL
dotgo.clientId=1x0kiKmR0Sd1WJuU
dotgo.clientSecert=DMeId0u9PZpKiPVWXaZTwnq61dA9OZew


dotgo.checkUrl=https://api.dotgo.com/rcs/bot/v1/%Bot_Id%/contactCapabilities?userContact=%Mobile%
dotgo.bulkCapabilityUrl=https://api.dotgo.com/rcs/bot/v1/%Bot_Id%/rcsEnabledContacts
vodafone.url.sent.message=https://api.virbm.com/rcs/v1/phones/%Mobile%/agentMessages/async?botId=%Bot_Id%&messageId=%MSG_Id%
vodafone.auth=https://api.virbm.com/rcs/oauth/token?grant_type=client_credentials
vodafone.checkUrl=https://api.virbm.com/rcs/v1/phones/%Mobile%/capabilities?botId=%Bot_Id%&requestId=%request_id%
vodafone.bulkCapabilityUrl=https://api.virbm.com/rcs/v1/phones/capabilities/bulk?botId=%bot_id%&requestId=%request_id%
jio.url.sent.message=https://stg-msg-businessmessaging.jio.com/v1/messaging/users/%Mobile%/assistantMessages/async
jio.auth=https://stg-tgs-businessmessaging.jio.com/auth/oauth/token?grant_type=client_credentials
jio.checkUrl=https://stg-msg-businessmessaging.jio.com/v1/messaging/users/%Mobile%/capabilities
jio.bulkCapabilityUrl=https://stg-msg-businessmessaging.jio.com/v1/messaging/usersBatchGet

# Register with Admin Server
spring.boot.admin.client.url=http://localhost:9999/admin
spring.boot.admin.client.instance.name=RCS Push API
spring.boot.admin.client.instance.prefer-ip=true

# Actuator settings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.health.mail.enabled=false
management.health.diskspace.enabled=true
management.health.db.enabled=true
jiocx.bulkCapabilityUrl=











